/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardPreviewRouteImport } from './routes/dashboard-preview'
import { Route as IndexRouteImport } from './routes/index'

const DashboardPreviewRoute = DashboardPreviewRouteImport.update({
  id: '/dashboard-preview',
  path: '/dashboard-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard-preview': typeof DashboardPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard-preview': typeof DashboardPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard-preview': typeof DashboardPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard-preview'
  id: '__root__' | '/' | '/dashboard-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardPreviewRoute: typeof DashboardPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard-preview': {
      id: '/dashboard-preview'
      path: '/dashboard-preview'
      fullPath: '/dashboard-preview'
      preLoaderRoute: typeof DashboardPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardPreviewRoute: DashboardPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
